language: python r
sudo: required
cache:
  pip: true
python:
- '3.5'
- '2.7'
r:
  - release
  - devel
  - oldrel
install:
- pip install pypairix
- pip install tox
- pip install coveralls 
- pip install codacy-coverage
r_github_packages: parklab/nozzle
script:
- bash tests/test.sh
after_success:
- python-codacy-coverage -r coverage.xml
- coveralls
